server:
  port: 8002
  servlet:
    context-path: /business

spring:
  application:
    name: business
  datasource:
    url: jdbc:mysql://localhost/train-business?useU-enicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fa221d

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    local-cache-scope: statement

logging:
  level:
    com:
      java:
        train:
          mapper: trace