GET http://localhost:8001/member/hello
Accept: application/json

###

GET http://localhost:8000/member/member/count
Accept: application/json

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=

###

POST http://localhost:8000/member/member/sendCode
Content-Type: application/x-www-form-urlencoded

mobile=13652708667

###

POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile=13652708667&code=1234

###